Added eachmoodhtml
NSS-Day-Cohort-69/macho-moods-serenity pull request #6
Opened 2024-01-31 20:32 UTC by Swathik22

2024-01-31 20:34 UTC, Lincoln-WIlcox requested changes

2024-01-31 20:34 UTC, Lincoln-WIlcox commented on scripts/moods.js
> +    let moodHTML=`<div class="moodbox"></div>`
class name should be cell, and put content within div

2024-02-01 19:29 UTC, joshuahamrick commented on scripts/moods.js
> +            <div class="moodName">${mood.name}</div>
Please put mood name before the mood image!

2024-02-01 19:29 UTC, joshuahamrick commented on scripts/moods.js
> +            <div class="moodQuotes">${mood.quotes[0]}\n ${mood.quotes[1]}</div>
please make a div to contain this div(#moodQuotes) and also a paragraph with the string "Macho Advice:"

2024-02-01 19:39 UTC, Lincoln-WIlcox approved these changes

2024-02-01 19:42 UTC, joshuahamrick approved these changes
Beautiful

2024-02-01 19:42 UTC, merged